# frozen_string_literal: true

# typed: true
LINE_1_OUTGOING_STATIONS = [
  'Sídliště Petřiny',
  'Petřiny',
  'Větrník',
  'Vojenská nemocnice',
  'Baterie',
  'Ořechovka',
  'Sibeliova',
  'Vozovna Střešovice (Muzeum MHD)',
  'Prašný most',
  'Hradčanská',
  'Sparta',
  'Letenské náměstí',
  'Kamenická',
  'Strossmayerovo náměstí',
  'Vltavská',
  'Pražská tržnice',
  'Dělnická',
  'Maniny',
  'Libeňský most',
  'Palmovka (ul. Zenklova)',
  'Krejcárek',
  'Ohrada',
  'Vozovna Žižkov',
  'Strážní',
  'Chmelnice',
  'Kněžská luka',
  'Spojovací'
].freeze

LINE_1_INCOMING_STATIONS = [
  'Spojovací',
  'Kněžská luka',
  'Chmelnice',
  'Strážní',
  'Vozovna Žižkov',
  'Ohrada',
  'Krejcárek',
  'Palmovka (předmostí Libeňského mostu)',
  'Libeňský most',
  'Maniny',
  'Tusarova',
  'Pražská tržnice',
  'Vltavská',
  'Strossmayerovo náměstí',
  'Kamenická',
  'Letenské náměstí',
  'Korunovační',
  'Sparta',
  'Hradčanská',
  'Prašný most',
  'Vozovna Střešovice (Muzeum MHD)',
  'Sibeliova',
  'Ořechovka',
  'Baterie',
  'Vojenská nemocnice',
  'Větrník',
  'Petřiny',
  'Sídliště Petřiny'
].freeze

LINE_2_OUTGOING_STATIONS = [
  'Sídliště Petřiny',
  'Petřiny',
  'Větrník',
  'Vojenská nemocnice',
  'Baterie',
  'Ořechovka',
  'Sibeliova',
  'Vozovna Střešovice (Muzeum MHD)',
  'Prašný most',
  'Hradčanská',
  'Chotkovy sady',
  'Malostranská',
  'Staroměstská',
  'Karlovy lázně',
  'Národní divadlo',
  'Národní třída',
  'Karlovo náměstí',
  'Moráň',
  'Palackého náměstí',
  'Palackého náměstí (nábřeží)',
  'Výtoň',
  'Podolská vodárna',
  'Kublov',
  'Dvorce',
  'Přístaviště',
  'Pobřežní cesta',
  'Nádraží Braník'
].freeze

LINE_2_INCOMING_STATIONS = [
  'Nádraží Braník',
  'Pobřežní cesta',
  'Přístaviště',
  'Dvorce',
  'Kublov',
  'Podolská vodárna',
  'Výtoň',
  'Palackého náměstí (nábřeží)',
  'Palackého náměstí',
  'Karlovo náměstí',
  'Novoměstská radnice',
  'Národní třída',
  'Národní divadlo',
  'Národní divadlo (nábřeží)',
  'Staroměstská',
  'Malostranská',
  'Chotkovy sady',
  'Hradčanská',
  'Prašný most',
  'Vozovna Střešovice (Muzeum MHD)',
  'Sibeliova',
  'Ořechovka',
  'Baterie',
  'Vojenská nemocnice',
  'Větrník',
  'Petřiny'
].freeze

LINE_3_OUTGOING_STATIONS = [
  'Levského',
  'Sídliště Modřany',
  'Modřanská rokle',
  'U Libušského potoka',
  'Poliklinika Modřany',
  'Čechova čtvrť',
  'Nádraží Modřany',
  'Modřanská škola',
  'Belárie',
  'Černý kůň',
  'Nádraží Braník',
  'Nádraží Braník',
  'Pobřežní cesta',
  'Přístaviště',
  'Dvorce',
  'Kublov',
  'Podolská vodárna',
  'Výtoň',
  'Palackého náměstí (nábřeží)',
  'Palackého náměstí',
  'Karlovo náměstí',
  'Novoměstská radnice',
  'Lazarská',
  'Vodičkova',
  'Václavské náměstí',
  'Jindřišská',
  'Masarykovo nádraží',
  'Bílá labuť',
  'Florenc',
  'Karlínské náměstí',
  'Křižíkova',
  'Urxova',
  'Invalidovna',
  'Palmovka (ul. Zenklova)',
  'Libeňský zámek',
  'U Kříže',
  'Vosmíkových',
  'Bulovka',
  'Vychovatelna',
  'Okrouhlická',
  'Ke Stírce',
  'Kobylisy'
].freeze

LINE_3_INCOMING_STATIONS = [
  'Březiněveská',
  'Kobylisy',
  'Ke Stírce',
  'Okrouhlická',
  'Vychovatelna',
  'Bulovka',
  'Vosmíkových',
  'U Kříže',
  'Libeňský zámek',
  'Divadlo pod Palmovkou',
  'Palmovka (ul. Zenklova)',
  'Invalidovna',
  'Urxova',
  'Křižíkova',
  'Karlínské náměstí',
  'Florenc',
  'Bílá labuť',
  'Masarykovo nádraží',
  'Jindřišská',
  'Václavské náměstí',
  'Vodičkova',
  'Lazarská',
  'Karlovo náměstí',
  'Moráň',
  'Palackého náměstí',
  'Palackého náměstí (nábřeží)',
  'Výtoň',
  'Podolská vodárna',
  'Kublov',
  'Dvorce',
  'Přístaviště',
  'Pobřežní cesta',
  'Nádraží Braník',
  'Černý kůň',
  'Belárie',
  'Modřanská škola',
  'Nádraží Modřany',
  'Čechova čtvrť',
  'Poliklinika Modřany',
  'U Libušského potoka',
  'Modřanská rokle',
  'Sídliště Modřany'
].freeze

LINE_4_OUTGOING_STATIONS = [
  'Sídliště Barrandov',
  'Poliklinika Barrandov',
  'Chaplinovo náměstí',
  'K Barrandovu',
  'Geologická',
  'Hlubočepy',
  'Zlíchov',
  'Lihovar',
  'Smíchovské nádraží',
  'Plzeňka',
  'Na Knížecí',
  'Anděl (ul. Nádražní)',
  'Zborovská',
  'Palackého náměstí',
  'Karlovo náměstí',
  'Štěpánská',
  'I. P. Pavlova',
  'Náměstí Míru',
  'Jana Masaryka',
  'Krymská',
  'Ruská',
  'Vršovické náměstí',
  'Čechovo náměstí'
].freeze

LINE_4_INCOMING_STATIONS = [
  'Čechovo náměstí',
  'Vršovické náměstí',
  'Ruská',
  'Krymská',
  'Jana Masaryka',
  'Náměstí Míru',
  'I. P. Pavlova',
  'Štěpánská',
  'Karlovo náměstí',
  'Moráň',
  'Palackého náměstí',
  'Zborovská',
  'Anděl (ul. Nádražní)',
  'Na Knížecí',
  'Plzeňka',
  'Smíchovské nádraží',
  'Lihovar',
  'Zlíchov',
  'Hlubočepy',
  'Geologická',
  'K Barrandovu',
  'Chaplinovo náměstí',
  'Poliklinika Barrandov',
  'Sídliště Barrandov'
].freeze

LINE_5_OUTGOING_STATIONS = [
  'Sídliště Barrandov',
  'Poliklinika Barrandov',
  'Chaplinovo náměstí',
  'K Barrandovu',
  'Geologická',
  'Hlubočepy',
  'Zlíchov',
  'Lihovar',
  'Smíchovské nádraží',
  'Plzeňka',
  'Na Knížecí',
  'Anděl (ul. Nádražní)',
  'Zborovská',
  'Jiráskovo náměstí',
  'Myslíkova',
  'Lazarská',
  'Vodičkova',
  'Václavské náměstí',
  'Jindřišská',
  'Hlavní nádraží (ul.Bolzanova)',
  'Husinecká',
  'Lipanská',
  'Olšanské náměstí',
  'Flora',
  'Olšanské hřbitovy',
  'Želivského (Vinohradská - západ)',
  'Želivského (Vinohradská - východ)',
  'Vinohradské hřbitovy',
  'Krematorium Strašnice',
  'Vinice',
  'Solidarita',
  'Zborov - Strašnické divadlo',
  'Nové Strašnice',
  'Černokostelecká',
  'Depo Hostivař (ul.Černokostelecká)',
  'Malešická továrna',
  'Na Homoli',
  'Ústřední dílny DP'
].freeze

LINE_5_INCOMING_STATIONS = [
  'Ústřední dílny DP',
  'Na Homoli',
  'Malešická továrna',
  'Depo Hostivař (ul.Černokostelecká)',
  'Černokostelecká',
  'Nové Strašnice',
  'Zborov - Strašnické divadlo',
  'Solidarita',
  'Vinice',
  'Krematorium Strašnice',
  'Vinohradské hřbitovy',
  'Želivského (Vinohradská - východ)',
  'Želivského (Vinohradská - západ)',
  'Olšanské hřbitovy',
  'Flora',
  'Olšanské náměstí',
  'Lipanská',
  'Husinecká',
  'Hlavní nádraží (ul.Bolzanova)',
  'Jindřišská',
  'Václavské náměstí',
  'Vodičkova',
  'Lazarská',
  'Myslíkova',
  'Jiráskovo náměstí',
  'Zborovská',
  'Anděl (ul. Nádražní)',
  'Na Knížecí',
  'Plzeňka',
  'Smíchovské nádraží',
  'Lihovar',
  'Zlíchov',
  'Hlubočepy',
  'Geologická',
  'K Barrandovu',
  'Chaplinovo náměstí',
  'Poliklinika Barrandov',
  'Sídliště Barrandov'
].freeze

LINE_6_OUTGOING_STATIONS = [
  'Palmovka (předmostí Libeňského mostu)',
  'Libeňský most',
  'Maniny',
  'U Průhonu',
  'Ortenovo náměstí',
  'Nádraží Holešovice',
  'Výstaviště Holešovice',
  'Veletržní palác',
  'Strossmayerovo náměstí',
  'Nábřeží Kapitána Jaroše',
  'Dlouhá třída',
  'Náměstí Republiky',
  'Masarykovo nádraží',
  'Jindřišská',
  'Václavské náměstí',
  'Vodičkova',
  'Lazarská',
  'Karlovo náměstí',
  'Štěpánská',
  'I. P. Pavlova',
  'Bruselská',
  'Pod Karlovem',
  'Nuselské schody',
  'Otakarova',
  'Nádraží Vršovice',
  'Bohemians',
  'Koh-i-noor',
  'Slavia',
  'Kubánské náměstí'
].freeze

LINE_6_INCOMING_STATIONS = [
  'Kubánské náměstí',
  'Slavia',
  'Koh-i-noor',
  'Bohemians',
  'Nádraží Vršovice',
  'Otakarova',
  'Nuselské schody',
  'Pod Karlovem',
  'Bruselská',
  'I. P. Pavlova',
  'Štěpánská',
  'Karlovo náměstí',
  'Novoměstská radnice',
  'Lazarská',
  'Vodičkova',
  'Václavské náměstí',
  'Jindřišská',
  'Masarykovo nádraží',
  'Náměstí Republiky',
  'Dlouhá třída',
  'Strossmayerovo náměstí',
  'Veletržní palác',
  'Výstaviště Holešovice',
  'Nádraží Holešovice',
  'Ortenovo náměstí',
  'Dělnická',
  'Maniny',
  'Libeňský most',
  'Palmovka (ul. Zenklova)'
].freeze

LINE_7_OUTGOING_STATIONS = [
  'Radlická',
  'Škola Radlice',
  'Laurová',
  'Braunova',
  'Křížová',
  'Na Knížecí (ul. Za Ženskými domovy)',
  'Anděl (ul. Nádražní)',
  'Zborovská',
  'Palackého náměstí (nábřeží)',
  'Výtoň',
  'Albertov',
  'Ostrčilovo náměstí',
  'Svatoplukova',
  'Divadlo Na Fidlovačce',
  'Otakarova',
  'Nádraží Vršovice',
  'Bohemians',
  'Koh-i-noor',
  'Slavia',
  'Kubánské náměstí',
  'Průběžná',
  'Strašnická',
  'Vozovna Strašnice',
  'Vinice',
  'Solidarita',
  'Zborov - Strašnické divadlo',
  'Nové Strašnice',
  'Černokostelecká'
].freeze

LINE_7_INCOMING_STATIONS = [
  'Černokostelecká',
  'Nové Strašnice',
  'Zborov - Strašnické divadlo',
  'Solidarita',
  'Vozovna Strašnice',
  'Strašnická',
  'Průběžná',
  'Kubánské náměstí',
  'Slavia',
  'Koh-i-noor',
  'Bohemians',
  'Nádraží Vršovice',
  'Otakarova',
  'Divadlo Na Fidlovačce',
  'Svatoplukova',
  'Ostrčilovo náměstí',
  'Albertov',
  'Výtoň',
  'Palackého náměstí (nábřeží)',
  'Zborovská',
  'Anděl (ul. Nádražní)',
  'Na Knížecí (ul. Za Ženskými domovy)',
  'Křížová',
  'Braunova',
  'Laurová',
  'Škola Radlice',
  'Radlická'
].freeze

LINE_8_OUTGOING_STATIONS = [
  'Nádraží Podbaba ',
  'Zelená ',
  'Lotyšská ',
  'Vítězné náměstí ',
  'Hradčanská ',
  'Sparta ',
  'Letenské náměstí ',
  'Kamenická ',
  'Strossmayerovo náměstí ',
  'Nábřeží Kapitána Jaroše ',
  'Dlouhá třída ',
  'Náměstí Republiky ',
  'Bílá labuť ',
  'Florenc ',
  'Karlínské náměstí ',
  'Křižíkova ',
  'Urxova ',
  'Invalidovna ',
  'Palmovka (ul. Na Žertvách) ',
  'Balabenka ',
  'Ocelářská ',
  'Multiaréna Praha ',
  'Nádraží Libeň ',
  'Kabešova ',
  'Podkovářská ',
  'U Elektry ',
  'Nademlejnská ',
  'Zelená ',
  'Starý Hloubětín'
].freeze

LINE_8_INCOMING_STATIONS = [
  'Starý Hloubětín ',
  'Nademlejnská ',
  'U Elektry ',
  'Podkovářská ',
  'Kabešova ',
  'Nádraží Libeň ',
  'Multiaréna Praha ',
  'Ocelářská ',
  'Balabenka ',
  'Palmovka (ul. Na Žertvách) ',
  'Palmovka (ul. Zenklova) ',
  'Invalidovna ',
  'Urxova ',
  'Křižíkova ',
  'Karlínské náměstí ',
  'Florenc ',
  'Bílá labuť ',
  'Náměstí Republiky ',
  'Dlouhá třída ',
  'Strossmayerovo náměstí ',
  'Kamenická ',
  'Letenské náměstí ',
  'Korunovační ',
  'Sparta ',
  'Hradčanská ',
  'Vítězné náměstí ',
  'Lotyšská ',
  'Nádraží Podbaba'
].freeze

LINE_9_OUTGOING_STATIONS = [
  'Sídliště Řepy',
  'Blatiny',
  'Slánská',
  'Hlušičkova',
  'Krematorium Motol',
  'Motol',
  'Vozovna Motol',
  'Hotel Golf',
  'Poštovka',
  'Kotlářka 1',
  'Kavalírka',
  'Klamovka',
  'U Zvonu',
  'Bertramka',
  'Anděl (ul. Plzeňská)',
  'Arbesovo náměstí',
  'Švandovo divadlo',
  'Újezd',
  'Národní divadlo',
  'Národní třída',
  'Lazarská',
  'Vodičkova',
  'Václavské náměstí',
  'Jindřišská',
  'Hlavní nádraží (ul.Bolzanova)',
  'Husinecká',
  'Lipanská',
  'Olšanské náměstí',
  'Olšanská',
  'Nákladové nádraží Žižkov (ul. Olšanská)',
  'Nákladové nádraží Žižkov',
  'Biskupcova',
  'Ohrada',
  'Vozovna Žižkov',
  'Strážní',
  'Chmelnice',
  'Kněžská luka',
  'Spojovací'
].freeze

LINE_9_INCOMING_STATIONS = [
  'Spojovací',
  'Kněžská luka',
  'Chmelnice',
  'Strážní',
  'Vozovna Žižkov',
  'Ohrada',
  'Biskupcova',
  'Nákladové nádraží Žižkov',
  'Nákladové nádraží Žižkov (ul. Olšanská)',
  'Olšanská',
  'Olšanské náměstí',
  'Lipanská',
  'Husinecká',
  'Hlavní nádraží (ul.Bolzanova)',
  'Jindřišská',
  'Václavské náměstí',
  'Vodičkova',
  'Lazarská',
  'Národní třída',
  'Národní divadlo',
  'Újezd',
  'Švandovo divadlo',
  'Arbesovo náměstí',
  'Anděl (ul. Plzeňská)',
  'Bertramka',
  'U Zvonu',
  'Klamovka',
  'Kavalírka',
  'Kotlářka 1',
  'Poštovka',
  'Hotel Golf',
  'Vozovna Motol',
  'Motol',
  'Krematorium Motol',
  'Hlušičkova',
  'Slánská',
  'Blatiny',
  'Sídliště Řepy'
].freeze

LINE_10_OUTGOING_STATIONS = [
  'Sídliště Řepy',
  'Blatiny',
  'Slánská',
  'Hlušičkova',
  'Krematorium Motol',
  'Motol',
  'Vozovna Motol',
  'Hotel Golf',
  'Poštovka',
  'Kotlářka 1',
  'Kavalírka',
  'Klamovka',
  'U Zvonu',
  'Bertramka',
  'Anděl (ul. Plzeňská)',
  'Zborovská',
  'Palackého náměstí',
  'Karlovo náměstí',
  'Štěpánská',
  'I. P. Pavlova',
  'Náměstí Míru',
  'Šumavská',
  'Vinohradská vodárna',
  'Perunova',
  'Orionka',
  'Flora',
  'Olšanské hřbitovy',
  'Želivského (Vinohradská - západ)',
  'Mezi Hřbitovy',
  'Nákladové nádraží Žižkov',
  'Biskupcova',
  'Krejcárek',
  'Palmovka (ul. Zenklova)',
  'Libeňský zámek',
  'U Kříže',
  'Vosmíkových',
  'Bulovka',
  'Vychovatelna',
  'Okrouhlická',
  'Ke Stírce',
  'Kobylisy',
  'Střelničná',
  'Kyselova',
  'Ládví',
  'Štěpničná',
  'Sídliště Ďáblice'
].freeze

LINE_10_INCOMING_STATIONS = [
  'Sídliště Ďáblice',
  'Třebenická',
  'Štěpničná',
  'Ládví',
  'Kyselova',
  'Střelničná',
  'Kobylisy',
  'Ke Stírce',
  'Okrouhlická',
  'Vychovatelna',
  'Bulovka',
  'Vosmíkových',
  'U Kříže',
  'Libeňský zámek',
  'Divadlo pod Palmovkou',
  'Palmovka (ul. Zenklova)',
  'Krejcárek',
  'Biskupcova',
  'Nákladové nádraží Žižkov',
  'Mezi Hřbitovy',
  'Želivského (Vinohradská - západ)',
  'Olšanské hřbitovy',
  'Flora',
  'Orionka',
  'Perunova',
  'Vinohradská vodárna',
  'Šumavská',
  'Náměstí Míru',
  'I. P. Pavlova',
  'Štěpánská',
  'Karlovo náměstí',
  'Moráň',
  'Palackého náměstí',
  'Zborovská',
  'Anděl (ul. Plzeňská)',
  'Bertramka',
  'U Zvonu',
  'Klamovka',
  'Kavalírka',
  'Kotlářka 1',
  'Poštovka',
  'Hotel Golf',
  'Vozovna Motol',
  'Motol',
  'Krematorium Motol',
  'Hlušičkova',
  'Slánská',
  'Blatiny',
  'Sídliště Řepy'
].freeze

LINE_11_OUTGOING_STATIONS = [
  'Spořilov',
  'Teplárna Michle',
  'Chodovská',
  'Plynárna Michle',
  'Michelská',
  'Pod Jezerkou',
  'Horky',
  'Náměstí Bratří Synků',
  'Nuselské schody',
  'Pod Karlovem',
  'Bruselská',
  'I. P. Pavlova',
  'Muzeum',
  'Italská',
  'Vinohradská tržnice',
  'Jiřího z Poděbrad',
  'Radhošťská',
  'Flora',
  'Olšanské hřbitovy',
  'Želivského (Vinohradská - západ)',
  'Mezi Hřbitovy',
  'Nákladové nádraží Žižkov',
  'Biskupcova',
  'Ohrada',
  'Vozovna Žižkov',
  'Strážní',
  'Chmelnice',
  'Kněžská luka',
  'Spojovací'
].freeze

LINE_11_INCOMING_STATIONS = [
  'Spojovací',
  'Kněžská luka',
  'Chmelnice',
  'Strážní',
  'Vozovna Žižkov',
  'Ohrada',
  'Biskupcova',
  'Nákladové nádraží Žižkov',
  'Mezi Hřbitovy',
  'Želivského (Vinohradská - západ)',
  'Olšanské hřbitovy',
  'Flora',
  'Radhošťská',
  'Jiřího z Poděbrad',
  'Vinohradská tržnice',
  'Italská',
  'Muzeum',
  'I. P. Pavlova',
  'Bruselská',
  'Pod Karlovem',
  'Nuselské schody',
  'Náměstí Bratří Synků',
  'Horky',
  'Pod Jezerkou',
  'Michelská',
  'Plynárna Michle',
  'Chodovská',
  'Teplárna Michle',
  'Spořilov'
].freeze

LINE_12_OUTGOING_STATIONS = [
  'Sídliště Barrandov',
  'Poliklinika Barrandov',
  'Chaplinovo náměstí',
  'K Barrandovu',
  'Geologická',
  'Hlubočepy',
  'Zlíchov',
  'Lihovar',
  'Smíchovské nádraží',
  'Plzeňka',
  'Na Knížecí',
  'Anděl (ul. Nádražní)',
  'Arbesovo náměstí',
  'Švandovo divadlo',
  'Újezd',
  'Hellichova',
  'Malostranské náměstí',
  'Malostranská',
  'Chotkovy sady',
  'Sparta',
  'Letenské náměstí',
  'Kamenická',
  'Strossmayerovo náměstí',
  'Vltavská',
  'Pražská tržnice',
  'Dělnická',
  'U Průhonu',
  'Ortenovo náměstí',
  'Nádraží Holešovice',
  'Výstaviště Holešovice',
  'Poliklinika Barrandov',
  'Výstaviště Holešovice'
].freeze

LINE_12_INCOMING_STATIONS = [
  'Výstaviště Holešovice',
  'Výstaviště Holešovice',
  'Nádraží Holešovice',
  'Ortenovo náměstí',
  'Dělnická',
  'Tusarova',
  'Pražská tržnice',
  'Vltavská',
  'Strossmayerovo náměstí',
  'Kamenická',
  'Letenské náměstí',
  'Korunovační',
  'Sparta',
  'Chotkovy sady',
  'Malostranská',
  'Malostranské náměstí',
  'Hellichova',
  'Újezd',
  'Švandovo divadlo',
  'Arbesovo náměstí',
  'Anděl (ul. Nádražní)',
  'Na Knížecí',
  'Plzeňka',
  'Smíchovské nádraží',
  'Lihovar',
  'Zlíchov',
  'Hlubočepy',
  'Geologická',
  'K Barrandovu',
  'Chaplinovo náměstí',
  'Sídliště Barrandov'
].freeze

LINE_13_INCOMING_STATIONS = [
  'Čechovo náměstí',
  'Vršovické náměstí',
  'Ruská',
  'Krymská',
  'Jana Masaryka',
  'Náměstí Míru',
  'I. P. Pavlova',
  'Muzeum',
  'Italská',
  'Vinohradská tržnice',
  'Jiřího z Poděbrad',
  'Radhošťská',
  'Flora',
  'Olšanské hřbitovy',
  'Želivského (Vinohradská - západ)',
  'Želivského (Vinohradská - východ)',
  'Vinohradské hřbitovy',
  'Krematorium Strašnice',
  'Vinice',
  'Solidarita',
  'Zborov - Strašnické divadlo',
  'Nové Strašnice'
].freeze

LINE_13_OUTGOING_STATIONS = [
  'Černokostelecká',
  'Nové Strašnice',
  'Zborov - Strašnické divadlo',
  'Solidarita',
  'Vinice',
  'Krematorium Strašnice',
  'Vinohradské hřbitovy',
  'Želivského (Vinohradská - východ)',
  'Želivského (Vinohradská - západ)',
  'Olšanské hřbitovy',
  'Flora',
  'Radhošťská',
  'Jiřího z Poděbrad',
  'Vinohradská tržnice',
  'Italská',
  'Muzeum',
  'I. P. Pavlova',
  'Náměstí Míru',
  'Jana Masaryka',
  'Krymská',
  'Ruská',
  'Vršovické náměstí'
].freeze

LINE_14_INCOMING_STATIONS = [
  'Spořilov',
  'Teplárna Michle',
  'Chodovská',
  'Plynárna Michle',
  'Michelská',
  'Pod Jezerkou',
  'Horky',
  'Náměstí Bratří Synků',
  'Divadlo Na Fidlovačce',
  'Svatoplukova',
  'Ostrčilovo náměstí',
  'Albertov',
  'Botanická zahrada',
  'Karlovo náměstí',
  'Novoměstská radnice',
  'Lazarská',
  'Vodičkova',
  'Václavské náměstí',
  'Jindřišská',
  'Masarykovo nádraží',
  'Bílá labuť',
  'Těšnov',
  'Štvanice',
  'Vltavská',
  'Pražská tržnice',
  'Dělnická',
  'Maniny',
  'Libeňský most',
  'Palmovka (ul. Na Žertvách)',
  'Balabenka',
  'Divadlo Gong',
  'Poliklinika Vysočany',
  'Nádraží Vysočany'
].freeze

LINE_14_OUTGOING_STATIONS = [
  'Vysočanská',
  'Nádraží Vysočany',
  'Poliklinika Vysočany',
  'Divadlo Gong',
  'Balabenka',
  'Palmovka (ul. Na Žertvách)',
  'Palmovka (předmostí Libeňského mostu)',
  'Libeňský most',
  'Maniny',
  'Tusarova',
  'Pražská tržnice',
  'Vltavská',
  'Štvanice',
  'Těšnov',
  'Bílá labuť',
  'Masarykovo nádraží',
  'Jindřišská',
  'Václavské náměstí',
  'Vodičkova',
  'Lazarská',
  'Karlovo náměstí',
  'Moráň',
  'Botanická zahrada',
  'Albertov',
  'Ostrčilovo náměstí',
  'Svatoplukova',
  'Divadlo Na Fidlovačce',
  'Náměstí Bratří Synků',
  'Horky',
  'Pod Jezerkou',
  'Michelská',
  'Plynárna Michle',
  'Chodovská',
  'Teplárna Michle'
].freeze

LINE_15_INCOMING_STATIONS = [
  'Kotlářka 1',
  'Kotlářka 2',
  'Kavalírka',
  'Klamovka',
  'U Zvonu',
  'Bertramka',
  'Anděl (ul. Plzeňská)',
  'Arbesovo náměstí',
  'Švandovo divadlo',
  'Újezd',
  'Hellichova',
  'Malostranské náměstí',
  'Malostranská',
  'Čechův most',
  'Dlouhá třída',
  'Náměstí Republiky',
  'Masarykovo nádraží',
  'Hlavní nádraží (ul.Bolzanova)',
  'Husinecká',
  'Lipanská',
  'Olšanské náměstí',
  'Flora'
].freeze

LINE_15_OUTGOING_STATIONS = [
  'Olšanské hřbitovy',
  'Flora',
  'Olšanské náměstí',
  'Lipanská',
  'Husinecká',
  'Hlavní nádraží (ul.Bolzanova)',
  'Masarykovo nádraží',
  'Náměstí Republiky',
  'Dlouhá třída',
  'Čechův most',
  'Malostranská',
  'Malostranské náměstí',
  'Hellichova',
  'Újezd',
  'Švandovo divadlo',
  'Arbesovo náměstí',
  'Anděl (ul. Plzeňská)',
  'Bertramka',
  'U Zvonu',
  'Klamovka',
  'Kavalírka'
].freeze

LINE_16_INCOMING_STATIONS = [
  'Sídliště Řepy',
  'Blatiny',
  'Slánská',
  'Hlušičkova',
  'Krematorium Motol',
  'Motol',
  'Vozovna Motol',
  'Hotel Golf',
  'Poštovka',
  'Kotlářka 1',
  'Kotlářka 2',
  'Kavalírka',
  'Klamovka',
  'U Zvonu',
  'Bertramka',
  'Anděl (ul. Plzeňská)',
  'Zborovská',
  'Palackého náměstí',
  'Karlovo náměstí',
  'Štěpánská',
  'I. P. Pavlova',
  'Náměstí Míru',
  'Šumavská',
  'Vinohradská vodárna',
  'Perunova',
  'Orionka',
  'Flora',
  'Olšanské hřbitovy',
  'Želivského (Vinohradská - západ)',
  'Mezi Hřbitovy',
  'Nákladové nádraží Žižkov',
  'Biskupcova',
  'Krejcárek',
  'Palmovka (ul. Na Žertvách)',
  'Balabenka',
  'Divadlo Gong',
  'Poliklinika Vysočany',
  'Nádraží Vysočany',
  'Vysočanská',
  'Špitálská',
  'Poštovská',
  'Kolbenova',
  'Nový Hloubětín',
  'Vozovna Hloubětín',
  'Starý Hloubětín',
  'Kbelská',
  'Hloubětín',
  'Sídliště Hloubětín'
].freeze

LINE_16_OUTGOING_STATIONS = [
  'Lehovec',
  'Sídliště Hloubětín',
  'Hloubětín',
  'Kbelská',
  'Starý Hloubětín',
  'Vozovna Hloubětín',
  'Nový Hloubětín',
  'Kolbenova',
  'Poštovská',
  'Špitálská',
  'Nádraží Vysočany',
  'Poliklinika Vysočany',
  'Divadlo Gong',
  'Balabenka',
  'Palmovka (ul. Na Žertvách)',
  'Palmovka (ul. Zenklova)',
  'Krejcárek',
  'Biskupcova',
  'Nákladové nádraží Žižkov',
  'Mezi Hřbitovy',
  'Želivského (Vinohradská - západ)',
  'Olšanské hřbitovy',
  'Flora',
  'Orionka',
  'Perunova',
  'Vinohradská vodárna',
  'Šumavská',
  'Náměstí Míru',
  'I. P. Pavlova',
  'Štěpánská',
  'Karlovo náměstí',
  'Moráň',
  'Palackého náměstí',
  'Zborovská',
  'Anděl (ul. Plzeňská)',
  'Bertramka',
  'U Zvonu',
  'Klamovka',
  'Kavalírka',
  'Kotlářka 1',
  'Poštovka',
  'Hotel Golf',
  'Vozovna Motol',
  'Motol',
  'Krematorium Motol',
  'Hlušičkova',
  'Slánská',
  'Blatiny'
].freeze

LINE_17_INCOMING_STATIONS = [
  'Levského',
  'Sídliště Modřany',
  'Modřanská rokle',
  'U Libušského potoka',
  'Poliklinika Modřany',
  'Čechova čtvrť',
  'Nádraží Modřany',
  'Modřanská škola',
  'Belárie',
  'Černý kůň',
  'Nádraží Braník',
  'Pobřežní cesta',
  'Přístaviště',
  'Dvorce',
  'Kublov',
  'Podolská vodárna',
  'Výtoň',
  'Palackého náměstí (nábřeží)',
  'Jiráskovo náměstí',
  'Národní divadlo (nábřeží)',
  'Staroměstská',
  'Právnická fakulta',
  'Čechův most',
  'Strossmayerovo náměstí',
  'Veletržní palác',
  'Výstaviště Holešovice',
  'Nádraží Holešovice',
  'Trojská',
  'Nad Trojou',
  'Hercovka',
  'Ke Stírce',
  'Kobylisy',
  'Březiněveská',
  'Líbeznická'
].freeze

LINE_17_OUTGOING_STATIONS = [
  'Vozovna Kobylisy',
  'Vozovna Kobylisy (ul. Klapkova)',
  'Líbeznická',
  'Březiněveská',
  'Kobylisy',
  'Ke Stírce',
  'Hercovka',
  'Nad Trojou',
  'Trojská',
  'Nádraží Holešovice',
  'Výstaviště Holešovice',
  'Výstaviště Holešovice',
  'Veletržní palác',
  'Strossmayerovo náměstí',
  'Nábřeží Kapitána Jaroše',
  'Čechův most',
  'Právnická fakulta',
  'Staroměstská',
  'Karlovy lázně',
  'Národní divadlo (nábřeží)',
  'Jiráskovo náměstí',
  'Palackého náměstí (nábřeží)',
  'Výtoň',
  'Podolská vodárna',
  'Kublov',
  'Dvorce',
  'Přístaviště',
  'Pobřežní cesta',
  'Nádraží Braník',
  'Černý kůň',
  'Belárie',
  'Modřanská škola',
  'Nádraží Modřany',
  'Čechova čtvrť',
  'Poliklinika Modřany',
  'U Libušského potoka',
  'Modřanská rokle'
].freeze

LINE_18_INCOMING_STATIONS = [
  'Nádraží Podbaba',
  'Zelená',
  'Lotyšská',
  'Vítězné náměstí',
  'Hradčanská',
  'Chotkovy sady',
  'Malostranská',
  'Staroměstská',
  'Karlovy lázně',
  'Národní divadlo',
  'Národní třída',
  'Karlovo náměstí',
  'Moráň',
  'Botanická zahrada',
  'Albertov',
  'Ostrčilovo náměstí',
  'Svatoplukova',
  'Divadlo Na Fidlovačce',
  'Náměstí Bratří Synků',
  'Nuselská radnice',
  'Palouček',
  'Pražského povstání',
  'Na Veselí'
].freeze

LINE_18_OUTGOING_STATIONS = [
  'Vozovna Pankrác',
  'Na Veselí',
  'Pražského povstání',
  'Palouček',
  'Nuselská radnice',
  'Náměstí Bratří Synků',
  'Divadlo Na Fidlovačce',
  'Svatoplukova',
  'Ostrčilovo náměstí',
  'Albertov',
  'Botanická zahrada',
  'Karlovo náměstí',
  'Novoměstská radnice',
  'Národní třída',
  'Národní divadlo',
  'Národní divadlo (nábřeží)',
  'Staroměstská',
  'Malostranská',
  'Chotkovy sady',
  'Hradčanská',
  'Vítězné náměstí',
  'Lotyšská',
  'Zelená'
].freeze

LINE_20_INCOMING_STATIONS = [
  'Sídliště Barrandov',
  'Poliklinika Barrandov',
  'Chaplinovo náměstí',
  'K Barrandovu',
  'Geologická',
  'Hlubočepy',
  'Zlíchov',
  'Lihovar',
  'Smíchovské nádraží',
  'Plzeňka',
  'Na Knížecí',
  'Anděl (ul. Nádražní)',
  'Arbesovo náměstí',
  'Švandovo divadlo',
  'Újezd',
  'Hellichova',
  'Malostranské náměstí',
  'Malostranská',
  'Chotkovy sady',
  'Hradčanská',
  'Vítězné náměstí',
  'Dejvická',
  'Thákurova',
  'Hadovka',
  'Na Pískách',
  'Bořislavka',
  'Sídliště Červený Vrch',
  'Červený Vrch',
  'Nádraží Veleslavín',
  'Nad Džbánem',
  'Vozovna Vokovice'
].freeze

LINE_20_OUTGOING_STATIONS = [
  'Divoká Šárka',
  'Vozovna Vokovice',
  'Nad Džbánem',
  'Nádraží Veleslavín',
  'Červený Vrch',
  'Sídliště Červený Vrch',
  'Bořislavka',
  'Na Pískách',
  'Hadovka',
  'Thákurova',
  'Dejvická',
  'Vítězné náměstí',
  'Hradčanská',
  'Chotkovy sady',
  'Malostranská',
  'Malostranské náměstí',
  'Hellichova',
  'Újezd',
  'Švandovo divadlo',
  'Arbesovo náměstí',
  'Anděl (ul. Nádražní)',
  'Na Knížecí',
  'Plzeňka',
  'Smíchovské nádraží',
  'Lihovar',
  'Zlíchov',
  'Hlubočepy',
  'Geologická',
  'K Barrandovu',
  'Chaplinovo náměstí',
  'Poliklinika Barrandov'
].freeze

LINE_21_INCOMING_STATIONS = [
  'Levského',
  'Sídliště Modřany',
  'Modřanská rokle',
  'U Libušského potoka',
  'Poliklinika Modřany',
  'Čechova čtvrť',
  'Nádraží Modřany',
  'Modřanská škola',
  'Belárie',
  'Černý kůň',
  'Nádraží Braník',
  'Pobřežní cesta',
  'Přístaviště',
  'Dvorce',
  'Kublov',
  'Podolská vodárna',
  'Výtoň',
  'Palackého náměstí (nábřeží)',
  'Zborovská',
  'Anděl (ul. Nádražní)',
  'Na Knížecí (ul. Za Ženskými domovy)',
  'Křížová',
  'Braunova',
  'Laurová',
  'Škola Radlice'
].freeze

LINE_21_OUTGOING_STATIONS = [
  'Radlická',
  'Škola Radlice',
  'Laurová',
  'Braunova',
  'Křížová',
  'Na Knížecí (ul. Za Ženskými domovy)',
  'Anděl (ul. Nádražní)',
  'Zborovská',
  'Palackého náměstí (nábřeží)',
  'Výtoň',
  'Podolská vodárna',
  'Kublov',
  'Dvorce',
  'Přístaviště',
  'Pobřežní cesta',
  'Nádraží Braník',
  'Černý kůň',
  'Belárie',
  'Modřanská škola',
  'Nádraží Modřany',
  'Čechova čtvrť',
  'Poliklinika Modřany',
  'U Libušského potoka',
  'Modřanská rokle'
].freeze

LINE_22_INCOMING_STATIONS = [
  'Bílá Hora',
  'Malý Břevnov',
  'Obora Hvězda',
  'Vypich',
  'Říčanova',
  'Břevnovský klášter',
  'U Kaštanu',
  'Drinopol',
  'Marjánka',
  'Malovanka',
  'Pohořelec',
  'Brusnice',
  'Pražský hrad',
  'Královský letohrádek',
  'Malostranská',
  'Malostranské náměstí',
  'Hellichova',
  'Újezd',
  'Národní divadlo',
  'Národní třída',
  'Karlovo náměstí',
  'Štěpánská',
  'I. P. Pavlova',
  'Náměstí Míru',
  'Jana Masaryka',
  'Krymská',
  'Ruská',
  'Vršovické náměstí',
  'Čechovo náměstí',
  'Koh-i-noor',
  'Slavia',
  'Kubánské náměstí',
  'Průběžná',
  'Na Hroudě',
  'Nádraží Strašnice',
  'Radošovická',
  'Dubečská',
  'Na Padesátém',
  'Zahradní Město',
  'Sídliště Zahradní Město',
  'Obchodní centrum Hostivař',
  'Na Groši',
  'Hostivařská'
].freeze

LINE_22_OUTGOING_STATIONS = [
  'Nádraží Hostivař',
  'Hostivařská',
  'Na Groši',
  'Obchodní centrum Hostivař',
  'Sídliště Zahradní Město',
  'Zahradní Město',
  'Na Padesátém',
  'Dubečská',
  'Radošovická',
  'Radošovická',
  'Nádraží Strašnice',
  'Na Hroudě',
  'Průběžná',
  'Kubánské náměstí',
  'Kubánské náměstí',
  'Slavia',
  'Koh-i-noor',
  'Čechovo náměstí',
  'Vršovické náměstí',
  'Ruská',
  'Krymská',
  'Jana Masaryka',
  'Náměstí Míru',
  'I. P. Pavlova',
  'Štěpánská',
  'Karlovo náměstí',
  'Novoměstská radnice',
  'Národní třída',
  'Národní divadlo',
  'Újezd',
  'Hellichova',
  'Malostranské náměstí',
  'Malostranská',
  'Královský letohrádek',
  'Pražský hrad',
  'Brusnice',
  'Pohořelec',
  'Malovanka',
  'Marjánka',
  'Drinopol',
  'U Kaštanu',
  'Břevnovský klášter',
  'Říčanova',
  'Vypich',
  'Obora Hvězda',
  'Malý Břevnov'
].freeze

LINE_24_INCOMING_STATIONS = [
  'Březiněveská',
  'Kobylisy',
  'Ke Stírce',
  'Okrouhlická',
  'Vychovatelna',
  'Bulovka',
  'Vosmíkových',
  'U Kříže',
  'Libeňský zámek',
  'Divadlo pod Palmovkou',
  'Palmovka (ul. Zenklova)',
  'Invalidovna',
  'Urxova',
  'Křižíkova',
  'Karlínské náměstí',
  'Florenc',
  'Bílá labuť',
  'Masarykovo nádraží',
  'Jindřišská',
  'Václavské náměstí',
  'Vodičkova',
  'Lazarská',
  'Karlovo náměstí',
  'Moráň',
  'Botanická zahrada',
  'Albertov',
  'Ostrčilovo náměstí',
  'Svatoplukova',
  'Divadlo Na Fidlovačce',
  'Otakarova',
  'Nádraží Vršovice',
  'Bohemians',
  'Koh-i-noor',
  'Slavia'
].freeze

LINE_24_OUTGOING_STATIONS = [
  'Kubánské náměstí',
  'Slavia',
  'Koh-i-noor',
  'Bohemians',
  'Nádraží Vršovice',
  'Otakarova',
  'Divadlo Na Fidlovačce',
  'Svatoplukova',
  'Ostrčilovo náměstí',
  'Albertov',
  'Botanická zahrada',
  'Karlovo náměstí',
  'Novoměstská radnice',
  'Lazarská',
  'Vodičkova',
  'Václavské náměstí',
  'Jindřišská',
  'Masarykovo nádraží',
  'Bílá labuť',
  'Florenc',
  'Karlínské náměstí',
  'Křižíkova',
  'Urxova',
  'Invalidovna',
  'Palmovka (ul. Zenklova)',
  'Libeňský zámek',
  'U Kříže',
  'Vosmíkových',
  'Bulovka',
  'Vychovatelna',
  'Okrouhlická',
  'Ke Stírce'
].freeze

LINE_25_INCOMING_STATIONS = [
  'Bílá Hora',
  'Malý Břevnov',
  'Obora Hvězda',
  'Vypich',
  'Říčanova',
  'Břevnovský klášter',
  'U Kaštanu',
  'Drinopol',
  'Marjánka',
  'Malovanka',
  'Hládkov',
  'Vozovna Střešovice (Muzeum MHD)',
  'Prašný most',
  'Hradčanská',
  'Sparta',
  'Letenské náměstí',
  'Kamenická',
  'Strossmayerovo náměstí',
  'Vltavská',
  'Pražská tržnice',
  'Dělnická',
  'Maniny',
  'Libeňský most',
  'Palmovka (ul. Na Žertvách)',
  'Balabenka',
  'Ocelářská',
  'Multiaréna Praha',
  'Nádraží Libeň',
  'Kabešova',
  'Podkovářská',
  'U Elektry',
  'Nademlejnská',
  'Kbelská',
  'Hloubětín',
  'Sídliště Hloubětín'
].freeze

LINE_25_OUTGOING_STATIONS = [
  'Lehovec',
  'Sídliště Hloubětín',
  'Hloubětín',
  'Kbelská',
  'Nademlejnská',
  'U Elektry',
  'Podkovářská',
  'Kabešova',
  'Nádraží Libeň',
  'Multiaréna Praha',
  'Ocelářská',
  'Balabenka',
  'Palmovka (ul. Na Žertvách)',
  'Palmovka (předmostí Libeňského mostu)',
  'Libeňský most',
  'Maniny',
  'Tusarova',
  'Pražská tržnice',
  'Vltavská',
  'Strossmayerovo náměstí',
  'Kamenická',
  'Letenské náměstí',
  'Korunovační',
  'Sparta',
  'Hradčanská',
  'Prašný most',
  'Vozovna Střešovice (Muzeum MHD)',
  'Hládkov',
  'Malovanka',
  'Marjánka',
  'Drinopol',
  'U Kaštanu',
  'Břevnovský klášter',
  'Říčanova',
  'Vypich',
  'Obora Hvězda',
  'Malý Břevnov'
].freeze

LINE_26_INCOMING_STATIONS = [
  'Divoká Šárka',
  'Vozovna Vokovice',
  'Nad Džbánem',
  'Nádraží Veleslavín',
  'Červený Vrch',
  'Sídliště Červený Vrch',
  'Bořislavka',
  'Na Pískách',
  'Hadovka',
  'Thákurova',
  'Dejvická',
  'Vítězné náměstí',
  'Hradčanská',
  'Sparta',
  'Letenské náměstí',
  'Kamenická',
  'Strossmayerovo náměstí',
  'Nábřeží Kapitána Jaroše',
  'Dlouhá třída',
  'Náměstí Republiky',
  'Masarykovo nádraží',
  'Hlavní nádraží (ul.Bolzanova)',
  'Husinecká',
  'Lipanská',
  'Olšanské náměstí',
  'Olšanská',
  'Nákladové nádraží Žižkov (ul. Olšanská)',
  'Mezi Hřbitovy',
  'Želivského (Vinohradská - východ)',
  'Vinohradské hřbitovy',
  'Krematorium Strašnice',
  'Vozovna Strašnice',
  'Strašnická',
  'Na Hroudě',
  'Nádraží Strašnice',
  'Radošovická',
  'Dubečská',
  'Na Padesátém',
  'Zahradní Město',
  'Sídliště Zahradní Město',
  'Obchodní centrum Hostivař',
  'Na Groši',
  'Hostivařská'
].freeze

LINE_26_OUTGOING_STATIONS = [
  'Nádraží Hostivař',
  'Hostivařská',
  'Na Groši',
  'Obchodní centrum Hostivař',
  'Sídliště Zahradní Město',
  'Zahradní Město',
  'Na Padesátém',
  'Dubečská',
  'Radošovická',
  'Nádraží Strašnice',
  'Na Hroudě',
  'Strašnická',
  'Vozovna Strašnice',
  'Vinice',
  'Krematorium Strašnice',
  'Vinohradské hřbitovy',
  'Želivského (Vinohradská - východ)',
  'Mezi Hřbitovy',
  'Nákladové nádraží Žižkov (ul. Olšanská)',
  'Olšanská',
  'Olšanské náměstí',
  'Lipanská',
  'Husinecká',
  'Hlavní nádraží (ul.Bolzanova)',
  'Masarykovo nádraží',
  'Náměstí Republiky',
  'Dlouhá třída',
  'Strossmayerovo náměstí',
  'Kamenická',
  'Letenské náměstí',
  'Korunovační',
  'Sparta',
  'Hradčanská',
  'Vítězné náměstí',
  'Dejvická',
  'Thákurova',
  'Hadovka',
  'Na Pískách',
  'Bořislavka',
  'Sídliště Červený Vrch',
  'Červený Vrch',
  'Nádraží Veleslavín',
  'Nad Džbánem',
  'Vozovna Vokovice'
].freeze

ALL_LINES = [
  {
    name: 'Line 1 - outgoing',
    outgoing: true,
    station_names: LINE_1_OUTGOING_STATIONS
  },
  {
    name: 'Line 1 - incoming',
    outgoing: false,
    station_names: LINE_1_INCOMING_STATIONS
  },
  {
    name: 'Line 2 - outgoing',
    outgoing: true,
    station_names: LINE_2_OUTGOING_STATIONS
  },
  {
    name: 'Line 2 - incoming',
    outgoing: false,
    station_names: LINE_2_INCOMING_STATIONS
  },
  {
    name: 'Line 3 - outgoing',
    outgoing: true,
    station_names: LINE_3_OUTGOING_STATIONS
  },
  {
    name: 'Line 3 - incoming',
    outgoing: false,
    station_names: LINE_3_INCOMING_STATIONS
  },
  {
    name: 'Line 4 - outgoing',
    outgoing: true,
    station_names: LINE_4_OUTGOING_STATIONS
  },
  {
    name: 'Line 4 - incoming',
    outgoing: false,
    station_names: LINE_4_INCOMING_STATIONS
  },
  {
    name: 'Line 5 - outgoing',
    outgoing: true,
    station_names: LINE_5_OUTGOING_STATIONS
  },
  {
    name: 'Line 5 - incoming',
    outgoing: false,
    station_names: LINE_5_INCOMING_STATIONS
  },
  {
    name: 'Line 6 - outgoing',
    outgoing: true,
    station_names: LINE_6_OUTGOING_STATIONS
  },
  {
    name: 'Line 6 - incoming',
    outgoing: false,
    station_names: LINE_6_INCOMING_STATIONS
  },
  {
    name: 'Line 7 - outgoing',
    outgoing: true,
    station_names: LINE_7_OUTGOING_STATIONS
  },
  {
    name: 'Line 7 - incoming',
    outgoing: false,
    station_names: LINE_7_INCOMING_STATIONS
  },
  {
    name: 'Line 8 - outgoing',
    outgoing: true,
    station_names: LINE_8_OUTGOING_STATIONS
  },
  {
    name: 'Line 8 - incoming',
    outgoing: false,
    station_names: LINE_8_INCOMING_STATIONS
  },
  {
    name: 'Line 9 - outgoing',
    outgoing: true,
    station_names: LINE_9_OUTGOING_STATIONS
  },
  {
    name: 'Line 9 - incoming',
    outgoing: false,
    station_names: LINE_9_INCOMING_STATIONS
  },
  {
    name: 'Line 10 - outgoing',
    outgoing: true,
    station_names: LINE_10_OUTGOING_STATIONS
  },
  {
    name: 'Line 10 - incoming',
    outgoing: false,
    station_names: LINE_10_INCOMING_STATIONS
  },
  {
    name: 'Line 11 - outgoing',
    outgoing: true,
    station_names: LINE_11_OUTGOING_STATIONS
  },
  {
    name: 'Line 11 - incoming',
    outgoing: false,
    station_names: LINE_11_INCOMING_STATIONS
  },
  {
    name: 'Line 12 - outgoing',
    outgoing: true,
    station_names: LINE_12_OUTGOING_STATIONS
  },
  {
    name: 'Line 12 - incoming',
    outgoing: false,
    station_names: LINE_12_INCOMING_STATIONS
  },
  {
    name: 'Line 13 - outgoing',
    outgoing: true,
    station_names: LINE_13_OUTGOING_STATIONS
  },
  {
    name: 'Line 13 - incoming',
    outgoing: false,
    station_names: LINE_13_INCOMING_STATIONS
  },
  {
    name: 'Line 14 - outgoing',
    outgoing: true,
    station_names: LINE_14_OUTGOING_STATIONS
  },
  {
    name: 'Line 14 - incoming',
    outgoing: false,
    station_names: LINE_14_INCOMING_STATIONS
  },
  {
    name: 'Line 15 - outgoing',
    outgoing: true,
    station_names: LINE_15_OUTGOING_STATIONS
  },
  {
    name: 'Line 15 - incoming',
    outgoing: false,
    station_names: LINE_15_INCOMING_STATIONS
  },
  {
    name: 'Line 16 - outgoing',
    outgoing: true,
    station_names: LINE_16_OUTGOING_STATIONS
  },
  {
    name: 'Line 16 - incoming',
    outgoing: false,
    station_names: LINE_16_INCOMING_STATIONS
  },
  {
    name: 'Line 17 - outgoing',
    outgoing: true,
    station_names: LINE_17_OUTGOING_STATIONS
  },
  {
    name: 'Line 17 - incoming',
    outgoing: false,
    station_names: LINE_17_INCOMING_STATIONS
  },
  {
    name: 'Line 18 - outgoing',
    outgoing: true,
    station_names: LINE_18_OUTGOING_STATIONS
  },
  {
    name: 'Line 18 - incoming',
    outgoing: false,
    station_names: LINE_18_INCOMING_STATIONS
  },
  {
    name: 'Line 20 - outgoing',
    outgoing: true,
    station_names: LINE_20_OUTGOING_STATIONS
  },
  {
    name: 'Line 20 - incoming',
    outgoing: false,
    station_names: LINE_20_INCOMING_STATIONS
  },
  {
    name: 'Line 21 - outgoing',
    outgoing: true,
    station_names: LINE_21_OUTGOING_STATIONS
  },
  {
    name: 'Line 21 - incoming',
    outgoing: false,
    station_names: LINE_21_INCOMING_STATIONS
  },
  {
    name: 'Line 22 - outgoing',
    outgoing: true,
    station_names: LINE_22_OUTGOING_STATIONS
  },
  {
    name: 'Line 22 - incoming',
    outgoing: false,
    station_names: LINE_22_INCOMING_STATIONS
  },
  {
    name: 'Line 24 - outgoing',
    outgoing: true,
    station_names: LINE_24_OUTGOING_STATIONS
  },
  {
    name: 'Line 24 - incoming',
    outgoing: false,
    station_names: LINE_24_INCOMING_STATIONS
  },
  {
    name: 'Line 25 - outgoing',
    outgoing: true,
    station_names: LINE_25_OUTGOING_STATIONS
  },
  {
    name: 'Line 25 - incoming',
    outgoing: false,
    station_names: LINE_25_INCOMING_STATIONS
  },
  {
    name: 'Line 26 - outgoing',
    outgoing: true,
    station_names: LINE_26_OUTGOING_STATIONS
  },
  {
    name: 'Line 26 - incoming',
    outgoing: false,
    station_names: LINE_26_INCOMING_STATIONS
  }
].freeze
