LINE_1 = [
  'Sídliště Petřiny',
  'Petřiny',
  'Větrník',
  'Vojenská nemocnice',
  'Baterie',
  'Ořechovka',
  'Sibeliova',
  'Vozovna Střešovice (Muzeum MHD)',
  'Prašný most',
  'Hradčanská',
  'Sparta',
  'Letenské náměstí',
  'Kamenická',
  'Strossmayerovo náměstí',
  'Vltavská',
  'Pražská tržnice',
  'Dělnická',
  'Maniny',
  'Libeňský most',
  'Palmovka (ul. Zenklova)',
  'Krejcárek',
  'Ohrada',
  'Vozovna Žižkov',
  'Strážní',
  'Chmelnice',
  'Kněžská luka',
]

LINE_2 = [
  'Sídliště Petřiny',
  'Petřiny',
  'Větrník',
  'Vojenská nemocnice',
  'Baterie',
  'Ořechovka',
  'Sibeliova',
  'Vozovna Střešovice (Muzeum MHD)',
  'Prašný most',
  'Hradčanská',
  'Chotkovy sady',
  'Malostranská',
  'Staroměstská',
  'Karlovy lázně',
  'Národní divadlo',
  'Národní třída',
  'Karlovo náměstí',
  'Moráň',
  'Palackého náměstí',
  'Palackého náměstí (nábřeží)',
  'Výtoň',
  'Podolská vodárna',
  'Kublov',
  'Dvorce',
  'Přístaviště',
  'Pobřežní cesta',
]

LINE_3 = [
  'Levského',
  'Sídliště Modřany',
  'Modřanská rokle',
  'U Libušského potoka',
  'Poliklinika Modřany',
  'Čechova čtvrť',
  'Nádraží Modřany',
  'Modřanská škola',
  'Belárie',
  'Černý kůň',
  'Nádraží Braník',
  'Pobřežní cesta',
  'Přístaviště',
  'Dvorce',
  'Kublov',
  'Podolská vodárna',
  'Výtoň',
  'Palackého náměstí (nábřeží)',
  'Palackého náměstí',
  'Karlovo náměstí',
  'Novoměstská radnice',
  'Lazarská',
  'Vodičkova',
  'Václavské náměstí',
  'Jindřišská',
  'Masarykovo nádraží',
  'Bílá labuť',
  'Florenc',
  'Karlínské náměstí',
  'Křižíkova',
  'Urxova',
  'Invalidovna',
  'Palmovka (ul. Zenklova)',
  'Libeňský zámek',
  'U Kříže',
  'Vosmíkových',
  'Bulovka',
  'Vychovatelna',
  'Okrouhlická',
  'Ke Stírce',
]

LINE_4 = [
  'Sídliště Barrandov',
  'Poliklinika Barrandov',
  'Chaplinovo náměstí',
  'K Barrandovu',
  'Geologická',
  'Hlubočepy',
  'Zlíchov',
  'Lihovar',
  'ČSAD Smíchov',
  'Smíchovské nádraží',
  'Plzeňka',
  'Na Knížecí',
  'Anděl (ul. Nádražní)',
  'Zborovská',
  'Palackého náměstí',
  'Karlovo náměstí',
  'Štěpánská',
  'I. P. Pavlova',
  'Náměstí Míru',
  'Jana Masaryka',
  'Krymská',
  'Ruská',
  'Vršovické náměstí',
]

LINE_5 = [
  'Sídliště Barrandov',
  'Poliklinika Barrandov',
  'Chaplinovo náměstí',
  'K Barrandovu',
  'Geologická',
  'Hlubočepy',
  'Zlíchov',
  'Lihovar',
  'ČSAD Smíchov',
  'Smíchovské nádraží',
  'Plzeňka',
  'Na Knížecí',
  'Anděl (ul. Nádražní)',
  'Zborovská',
  'Jiráskovo náměstí',
  'Myslíkova',
  'Lazarská',
  'Vodičkova',
  'Václavské náměstí',
  'Jindřišská',
  'Hlavní nádraží (ul.Bolzanova)',
  'Husinecká',
  'Lipanská',
  'Olšanské náměstí',
  'Flora',
  'Olšanské hřbitovy',
  'Želivského (Vinohradská - západ)',
  'Želivského (Vinohradská - východ)',
  'Vinohradské hřbitovy',
  'Krematorium Strašnice',
  'Vozovna Strašnice',
  'Vinice',
  'Solidarita',
  'Zborov - Strašnické divadlo',
  'Nové Strašnice',
  'Černokostelecká',
  'Depo Hostivař (ul.Černokostelecká)',
  'Malešická továrna',
  'Na Homoli',
]

LINE_6 = [
  'Palmovka (předmostí Libeňského mostu)',
  'Libeňský most',
  'Maniny',
  'U Průhonu',
  'Ortenovo náměstí',
  'Nádraží Holešovice',
  'Výstaviště Holešovice',
  'Veletržní palác',
  'Strossmayerovo náměstí',
  'Nábřeží Kapitána Jaroše',
  'Dlouhá třída',
  'Náměstí Republiky',
  'Masarykovo nádraží',
  'Jindřišská',
  'Václavské náměstí',
  'Vodičkova',
  'Lazarská',
  'Karlovo náměstí',
  'Štěpánská',
  'I. P. Pavlova',
  'Bruselská',
  'Pod Karlovem',
  'Nuselské schody',
  'Otakarova',
  'Nádraží Vršovice',
  'Bohemians',
  'Koh-i-noor',
  'Slavia',
]

LINE_7 = [
  'Radlická',
  'Škola Radlice',
  'Laurová',
  'Braunova',
  'Křížová',
  'Na Knížecí (ul. Za Ženskými domovy)',
  'Anděl (ul. Nádražní)',
  'Zborovská',
  'Palackého náměstí (nábřeží)',
  'Výtoň',
  'Albertov',
  'Ostrčilovo náměstí',
  'Svatoplukova',
  'Divadlo Na Fidlovačce',
  'Otakarova',
  'Nádraží Vršovice',
  'Bohemians',
  'Koh-i-noor',
  'Slavia',
  'Kubánské náměstí',
  'Průběžná',
  'Strašnická',
  'Vozovna Strašnice',
  'Vinice',
  'Solidarita',
  'Zborov - Strašnické divadlo',
  'Nové Strašnice',
]

LINE_8 = [
  'Nádraží Podbaba',
  'Zelená',
  'Lotyšská',
  'Vítězné náměstí',
  'Hradčanská',
  'Sparta',
  'Letenské náměstí',
  'Kamenická',
  'Strossmayerovo náměstí',
  'Nábřeží Kapitána Jaroše',
  'Dlouhá třída',
  'Náměstí Republiky',
  'Bílá labuť',
  'Florenc',
  'Karlínské náměstí',
  'Křižíkova',
  'Urxova',
  'Invalidovna',
  'Palmovka (ul. Na Žertvách)',
  'Balabenka',
  'Ocelářská',
  'Multiaréna Praha',
  'Nádraží Libeň',
  'Kabešova',
  'Podkovářská',
  'U Elektry',
  'Nademlejnská',
]

LINE_9 = [
  'Sídliště Řepy',
  'Blatiny',
  'Slánská',
  'Hlušičkova',
  'Krematorium Motol',
  'Motol',
  'Vozovna Motol',
  'Hotel Golf',
  'Poštovka',
  'Kotlářka',
  'Kavalírka',
  'Klamovka',
  'U Zvonu',
  'Bertramka',
  'Anděl (ul. Plzeňská)',
  'Arbesovo náměstí',
  'Švandovo divadlo',
  'Újezd',
  'Národní divadlo',
  'Národní třída',
  'Lazarská',
  'Vodičkova',
  'Václavské náměstí',
  'Jindřišská',
  'Hlavní nádraží (ul.Bolzanova)',
  'Husinecká',
  'Lipanská',
  'Olšanské náměstí',
  'Olšanská',
  'Nákladové nádraží Žižkov (ul. Olšanská)',
  'Nákladové nádraží Žižkov',
  'Biskupcova',
  'Ohrada',
  'Vozovna Žižkov',
  'Strážní',
  'Chmelnice',
  'Kněžská luka',
]

LINE_10 = [
  'Sídliště Řepy',
  'Blatiny',
  'Slánská',
  'Hlušičkova',
  'Krematorium Motol',
  'Motol',
  'Vozovna Motol',
  'Hotel Golf',
  'Poštovka',
  'Kotlářka',
  'Kavalírka',
  'Klamovka',
  'U Zvonu',
  'Bertramka',
  'Anděl (ul. Plzeňská)',
  'Zborovská',
  'Palackého náměstí',
  'Karlovo náměstí',
  'Štěpánská',
  'I. P. Pavlova',
  'Náměstí Míru',
  'Šumavská',
  'Vinohradská vodárna',
  'Perunova',
  'Orionka',
  'Flora',
  'Olšanské hřbitovy',
  'Želivského (Vinohradská - západ)',
  'Mezi Hřbitovy',
  'Nákladové nádraží Žižkov',
  'Biskupcova',
  'Krejcárek',
  'Palmovka (ul. Zenklova)',
  'Libeňský zámek',
  'U Kříže',
  'Vosmíkových',
  'Bulovka',
  'Vychovatelna',
  'Okrouhlická',
  'Ke Stírce',
  'Kobylisy',
  'Střelničná',
  'Kyselova',
  'Ládví',
  'Štěpničná',
]

LINE_11 = [
  'Spořilov',
  'Teplárna Michle',
  'Chodovská',
  'Plynárna Michle',
  'Michelská',
  'Pod Jezerkou',
  'Horky',
  'Náměstí Bratří Synků',
  'Nuselské schody',
  'Pod Karlovem',
  'Bruselská',
  'I. P. Pavlova',
  'Muzeum',
  'Italská',
  'Vinohradská tržnice',
  'Jiřího z Poděbrad',
  'Radhošťská',
  'Flora',
  'Olšanské hřbitovy',
  'Želivského (Vinohradská - západ)',
  'Mezi Hřbitovy',
  'Nákladové nádraží Žižkov',
  'Biskupcova',
  'Ohrada',
  'Vozovna Žižkov',
  'Strážní',
  'Chmelnice',
  'Kněžská luka',
]

LINE_12 = [
  'Sídliště Barrandov',
  'Poliklinika Barrandov',
  'Chaplinovo náměstí',
  'K Barrandovu',
  'Geologická',
  'Hlubočepy',
  'Zlíchov',
  'Lihovar',
  'ČSAD Smíchov',
  'Smíchovské nádraží',
  'Plzeňka',
  'Na Knížecí',
  'Anděl (ul. Nádražní)',
  'Arbesovo náměstí',
  'Švandovo divadlo',
  'Újezd',
  'Hellichova',
  'Malostranské náměstí',
  'Malostranská',
  'Chotkovy sady',
  'Sparta',
  'Letenské náměstí',
  'Kamenická',
  'Strossmayerovo náměstí',
  'Vltavská',
  'Pražská tržnice',
  'Dělnická',
  'U Průhonu',
  'Ortenovo náměstí',
  'Nádraží Holešovice',
  'Výstaviště Holešovice',
]

ALL_LINES = [
  LINE_1,
  LINE_2,
  LINE_3,
  LINE_4,
  LINE_5,
  LINE_6,
  LINE_7,
  LINE_8,
  LINE_9,
  LINE_10,
  LINE_11,
  LINE_12,
]
